[package]
name = "wasm_explore"
version = "0.1.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
edition = "2018"

[dependencies]
serde = "~1.0.27"
serde_json = "1.0"
wasmi = "=0.4.2"
memory_units = "0.4"